const TOGGLE = "ui/TOGGLE_DRAWER";
const SHOW_MODAL = "ui/SHOW_MODAL";
const HIDE_MODAL = "ui/HIDE_MODAL";
const MODAL_TYPE = "ui/SHOW_MODAL/NOTEBOOK";

export {
  TOGGLE,
  SHOW_MODAL,
  HIDE_MODAL,
  MODAL_TYPE
};
