const TOGGLE = "ui/TOGGLE_DRAWER";
const SHOW_MODAL = "ui/SHOW_MODAL";
const HIDE_MODAL = "ui/HIDE_MODAL";
const NOTEBOOK_MODAL = "ui/SHOW_MODAL/NOTEBOOK";
const ATTACHMENT_MODAL = "ui/SHOW_MODAL/ATTACHMENT";
const MODAL_TYPE = "ui/SHOW_MODAL/NOTEBOOK";

export {
  MODAL_TYPE,
  TOGGLE,
  SHOW_MODAL,
  HIDE_MODAL,
  NOTEBOOK_MODAL,
  ATTACHMENT_MODAL
};
